import React,{useEffect,useMemo,useRef,useState} from "react";
import {apiDelete,apiGet,apiPost,apiPostForm} from "../services/api";
import {normalizeSearchText} from "../utils/filterUtils";
import ValueHelpField from "./ValueHelpField";
import "./DocumentManagement.css";

interface Announcement{id:string;title:string;message:string;linkUrl:string;imageUrl:string;publishAt:string;expiresAt:string;createdAt?:string;assignedCount:number;assignedUserIds:string[]}
interface Student{name:string;userId:string;email:string}

const toInputDateTime=(value:string)=>value?value.slice(0,16):"";
const announcementState=(item:Announcement)=>{const now=Date.now(),start=new Date(item.publishAt||item.createdAt||Date.now()).getTime(),end=item.expiresAt?new Date(item.expiresAt).getTime():Infinity;return start>now?"scheduled":end<now?"expired":"published"};

const AnnouncementManagement:React.FC=()=>{
 const [items,setItems]=useState<Announcement[]>([]),[students,setStudents]=useState<Student[]>([]),[title,setTitle]=useState(""),[message,setMessage]=useState(""),[linkUrl,setLinkUrl]=useState(""),[image,setImage]=useState<File|null>(null),[publishAt,setPublishAt]=useState(""),[expiresAt,setExpiresAt]=useState(""),[uploading,setUploading]=useState(false),[assigning,setAssigning]=useState<Announcement|null>(null),[selected,setSelected]=useState<string[]>([]),[studentSearch,setStudentSearch]=useState(""),[search,setSearch]=useState(""),[status,setStatus]=useState("all"),[showLink,setShowLink]=useState(false),[showImage,setShowImage]=useState(false),[notice,setNotice]=useState("");
 const imageRef=useRef<HTMLInputElement>(null);
 const load=async()=>{const [a,u]=await Promise.all([apiGet<{announcements:Announcement[]}>("/admin/announcements"),apiGet<{users:Student[]}>("/admin/users")]);setItems(a.announcements||[]);setStudents(u.users||[])};
 useEffect(()=>{load().catch(error=>setNotice(error?.message||"Could not load announcements"))},[]);
 const visibleStudents=useMemo(()=>{const query=normalizeSearchText(studentSearch);return students.filter(s=>normalizeSearchText(`${s.name} ${s.userId} ${s.email}`).includes(query))},[students,studentSearch]);
 const filtered=useMemo(()=>items.filter(item=>normalizeSearchText(`${item.title} ${item.message} ${item.linkUrl}`).includes(normalizeSearchText(search))&&(status==="all"||status===announcementState(item))),[items,search,status]);
 const reset=()=>{setTitle("");setMessage("");setLinkUrl("");setImage(null);setPublishAt("");setExpiresAt("");setShowLink(false);setShowImage(false);if(imageRef.current)imageRef.current.value=""};
 const publish=async()=>{setNotice("");const cleanTitle=title.trim(),cleanMessage=message.trim();if(!cleanTitle||!cleanMessage){setNotice("Enter both title and message before publishing.");return}if(publishAt&&expiresAt&&new Date(expiresAt)<=new Date(publishAt)){setNotice("Expire date must be after the publish date.");return}setUploading(true);try{const body=new FormData();body.append("title",cleanTitle);body.append("message",cleanMessage);body.append("linkUrl",linkUrl.trim());if(publishAt)body.append("publishAt",new Date(publishAt).toISOString());if(expiresAt)body.append("expiresAt",new Date(expiresAt).toISOString());if(image)body.append("image",image);await apiPostForm("/admin/announcements",body);reset();setNotice("Announcement published successfully.");await load()}catch(e:any){setNotice(e?.message||"Announcement could not be published")}finally{setUploading(false)}};
 const openAssign=(item:Announcement)=>{setAssigning(item);setSelected(item.assignedUserIds||[]);setStudentSearch("")};
 const save=async()=>{if(!assigning)return;try{await apiPost(`/admin/announcements/${assigning.id}/assign`,{userIds:selected});setAssigning(null);setNotice("Announcement assignment updated.");await load()}catch(error:any){setNotice(error?.message||"Announcement assignment could not be saved.")}};
 const remove=async(item:Announcement)=>{if(window.confirm(`Delete ${item.title}?`)){await apiDelete(`/admin/announcements/${item.id}`);setNotice("Announcement deleted.");await load()}};
 return <section className="document-admin"><header><div><span>STUDENT COMMUNICATIONS</span><h1>Announcements</h1><p>Publish student notices and schedule future update messages.</p></div></header>
 <div className="announcement-composer"><div className="composer-heading"><span>NEW ANNOUNCEMENT</span><h2>Create announcement</h2><p>Publish immediately or schedule a future student update.</p></div><div className="composer-fields"><label>Title<input value={title} onChange={e=>setTitle(e.target.value)} placeholder="Enter announcement title"/></label><label className="message-field">Message<textarea value={message} onChange={e=>setMessage(e.target.value)} placeholder="Write the announcement for students"/></label></div><div className="composer-attachments"><button type="button" className={showLink?"active":""} onClick={()=>setShowLink(value=>!value)}><b>＋</b><span>Add link<small>Attach a batch or information page</small></span></button><button type="button" className={showImage?"active":""} onClick={()=>setShowImage(value=>!value)}><b>▧</b><span>Upload image<small>PNG or JPG announcement banner</small></span></button></div>{showLink&&<label className="composer-expanded-field">Page link<input value={linkUrl} onChange={e=>setLinkUrl(e.target.value)} placeholder="https://example.com/future-test-update"/></label>}{showImage&&<div className="announcement-image-picker"><input ref={imageRef} type="file" accept=".png,.jpg,.jpeg" onChange={e=>setImage(e.target.files?.[0]||null)}/><button type="button" onClick={()=>imageRef.current?.click()}>↑ Upload image</button><span>{image?image.name:"No image selected"}</span>{image&&<button type="button" className="remove-picked-file" onClick={()=>{setImage(null);if(imageRef.current)imageRef.current.value=""}}>Remove</button>}</div>}<div className="composer-schedule"><label>Publish from<input type="datetime-local" value={toInputDateTime(publishAt)} onChange={e=>setPublishAt(e.target.value)}/><small>Leave empty to publish now</small></label><label>Expire on<input type="datetime-local" value={toInputDateTime(expiresAt)} onChange={e=>setExpiresAt(e.target.value)}/><small>Optional end date</small></label><button type="button" className="publish-announcement" disabled={uploading||!title.trim()||!message.trim()} onClick={publish}>{uploading?"Publishing…":"Publish announcement →"}</button></div>{notice&&<p className="announcement-notice">{notice}</p>}</div>
 <div className="document-filters value-help-document-filters"><ValueHelpField label="Search Announcements" placeholder="Search title, message or link" value={search} options={items.map(item=>({value:item.title,label:item.title,keywords:[item.message,item.linkUrl]}))} onChange={setSearch} allowFreeText/><ValueHelpField label="Status" placeholder="All statuses" value={status} options={[{value:"all",label:"All statuses"},{value:"published",label:"Published"},{value:"scheduled",label:"Scheduled"},{value:"expired",label:"Expired"}]} onChange={setStatus}/><button type="button" onClick={()=>{setSearch("");setStatus("all")}}>Clear filters</button></div><div className="document-grid">{filtered.map(item=><article key={item.id}><div className="document-type">NEWS</div><div className="document-copy"><h3>{item.title}</h3><p>{item.message}</p><span>{item.linkUrl||"No external page"} • {announcementState(item)}</span></div><div className="document-assigned"><strong>{item.assignedCount}</strong><span>students</span></div><button type="button" onClick={()=>openAssign(item)}>Assign</button><button type="button" className="danger" onClick={()=>remove(item)}>Delete</button></article>)}{filtered.length===0&&<div className="document-empty">No announcements match these filters.</div>}</div>
 {assigning&&<div className="document-modal-backdrop" onMouseDown={()=>setAssigning(null)}><div className="document-modal" onMouseDown={e=>e.stopPropagation()}><header><div><span>ASSIGN ANNOUNCEMENT</span><h2>{assigning.title}</h2></div><button type="button" onClick={()=>setAssigning(null)}>×</button></header><ValueHelpField label="Search Students" placeholder="Search name, username or email" value={studentSearch} options={students.map(student=>({value:student.name,label:student.name,keywords:[student.userId,student.email]}))} onChange={setStudentSearch} allowFreeText/><label className="select-all"><input type="checkbox" checked={visibleStudents.length>0&&visibleStudents.every(s=>selected.includes(s.userId))} onChange={e=>setSelected(e.target.checked?Array.from(new Set([...selected,...visibleStudents.map(s=>s.userId)])):selected.filter(id=>!visibleStudents.some(s=>s.userId===id)))}/> Select all visible students</label><div className="document-students">{visibleStudents.map(s=><label key={s.userId}><input type="checkbox" checked={selected.includes(s.userId)} onChange={e=>setSelected(e.target.checked?[...selected,s.userId]:selected.filter(id=>id!==s.userId))}/><span>{s.name}<small>{s.userId} • {s.email}</small></span></label>)}</div><footer><span>{selected.length} selected</span><button type="button" onClick={save}>Assign announcement</button></footer></div></div>}</section>
};

export default AnnouncementManagement;
