import React, { useEffect, useState } from "react";
import { apiDelete, apiGet, apiPost, apiPut } from "../services/api";
import "./ExamCategoryManagement.css";

export interface ExamSubcategory { id:string;name:string;slug:string;stages:string[];isActive?:boolean }
export interface ExamCategory { id:string;name:string;slug:string;order:number;isActive:boolean;subcategories:ExamSubcategory[] }

const ExamCategoryManagement:React.FC=()=>{
  const [categories,setCategories]=useState<ExamCategory[]>([]);
  const [name,setName]=useState("");
  const [drafts,setDrafts]=useState<Record<string,{name:string;stages:string}>>({});
  const [loading,setLoading]=useState(true);
  const [adding,setAdding]=useState(false);
  const [feedback,setFeedback]=useState<{type:"success"|"error";text:string}|null>(null);
  const load=async()=>{setLoading(true);try{const res=await apiGet<{categories:ExamCategory[]}>("/admin/exam-categories");setCategories(res.categories||[])}finally{setLoading(false)}};
  useEffect(()=>{load()},[]);
  const addCategory=async()=>{const categoryName=name.trim();if(!categoryName||adding){if(!categoryName)setFeedback({type:"error",text:"Enter a category name first."});return}setAdding(true);setFeedback(null);try{await apiPost("/admin/exam-categories",{name:categoryName,order:categories.length});setName("");await load();setFeedback({type:"success",text:`${categoryName} was added successfully.`})}catch(error:any){setFeedback({type:"error",text:error?.message||"Category could not be added. Check that the backend is running."})}finally{setAdding(false)}};
  const addSubcategory=async(categoryId:string)=>{const draft=drafts[categoryId]||{name:"",stages:"Prelims, Mains"};if(!draft.name.trim())return;try{await apiPost(`/admin/exam-categories/${categoryId}/subcategories`,{name:draft.name.trim(),stages:draft.stages.split(",").map(value=>value.trim()).filter(Boolean)});setDrafts(current=>({...current,[categoryId]:{name:"",stages:"Prelims, Mains"}}));await load()}catch(error:any){alert(error?.message||"Subcategory could not be added")}};
  const editCategory=async(category:ExamCategory)=>{const next=window.prompt("Category name",category.name)?.trim();if(!next||next===category.name)return;try{await apiPut(`/admin/exam-categories/${category.id}`,{name:next,order:category.order,isActive:category.isActive});await load()}catch(error:any){alert(error?.message||"Category could not be updated")}};
  const removeCategory=async(category:ExamCategory)=>{if(!window.confirm(`Delete ${category.name}?`))return;try{await apiDelete(`/admin/exam-categories/${category.id}`);await load()}catch(error:any){alert(error?.message||"Categories containing tests cannot be deleted")}};
  const editSubcategory=async(category:ExamCategory,sub:ExamSubcategory)=>{const nextName=window.prompt("Subcategory name",sub.name)?.trim();if(!nextName)return;const stages=window.prompt("Stages separated by commas",sub.stages.join(", "));if(stages===null)return;try{await apiPut(`/admin/exam-categories/${category.id}/subcategories/${sub.id}`,{name:nextName,stages:stages.split(",").map(value=>value.trim()).filter(Boolean),isActive:sub.isActive!==false});await load()}catch(error:any){alert(error?.message||"Subcategory could not be updated")}};
  const removeSubcategory=async(category:ExamCategory,sub:ExamSubcategory)=>{if(!window.confirm(`Delete ${sub.name}?`))return;try{await apiDelete(`/admin/exam-categories/${category.id}/subcategories/${sub.id}`);await load()}catch(error:any){alert(error?.message||"Subcategories containing tests cannot be deleted")}};
  return <section className="category-admin-page">
    <header><div><span>EXAM STRUCTURE</span><h1>Exam Categories</h1><p>Manage the hierarchy used in My Tests and during test creation.</p></div><form className="add-category" onSubmit={event=>{event.preventDefault();void addCategory()}}><input value={name} onChange={e=>{setName(e.target.value);setFeedback(null)}} placeholder="New category, e.g. Railway" aria-label="New category name"/><button type="submit" disabled={adding}>{adding?"Adding…":"+ Add category"}</button></form></header>
    {feedback&&<div className={`category-feedback ${feedback.type}`}>{feedback.type==="success"?"✓":"!"} {feedback.text}</div>}
    <div className="category-summary"><div><span>Categories</span><strong>{categories.length}</strong></div><div><span>Subcategories</span><strong>{categories.reduce((sum,item)=>sum+item.subcategories.length,0)}</strong></div><div><span>Stages</span><strong>{categories.reduce((sum,item)=>sum+item.subcategories.reduce((count,sub)=>count+sub.stages.length,0),0)}</strong></div></div>
    {loading?<div className="category-empty">Loading exam structure…</div>:categories.length===0?<div className="category-empty">Add your first exam category to begin.</div>:<div className="category-grid">{categories.map((category,index)=><article key={category.id} className="category-card"><div className="category-card-head"><span>{String(index+1).padStart(2,"0")}</span><div><h2>{category.name}</h2><small>{category.subcategories.length} subcategories</small></div><button onClick={()=>editCategory(category)}>Edit</button><button className="danger" onClick={()=>removeCategory(category)}>Delete</button></div><div className="subcategory-list">{category.subcategories.map(sub=><div key={sub.id} className="subcategory-row"><div><strong>{sub.name}</strong><span>{sub.stages.map(stage=><i key={stage}>{stage}</i>)}</span></div><button onClick={()=>editSubcategory(category,sub)}>Edit</button><button className="danger" onClick={()=>removeSubcategory(category,sub)}>×</button></div>)}</div><div className="add-subcategory"><input value={drafts[category.id]?.name||""} onChange={e=>setDrafts({...drafts,[category.id]:{name:e.target.value,stages:drafts[category.id]?.stages||"Prelims, Mains"}})} placeholder="New subcategory, e.g. RBI Grade B"/><input value={drafts[category.id]?.stages||"Prelims, Mains"} onChange={e=>setDrafts({...drafts,[category.id]:{name:drafts[category.id]?.name||"",stages:e.target.value}})} placeholder="Stages: Prelims, Mains"/><button onClick={()=>addSubcategory(category.id)}>Add</button></div></article>)}</div>}
  </section>;
};
export default ExamCategoryManagement;
