import React, { useEffect, useMemo, useState } from "react";
import { apiGet } from "../services/api";
import { normalizeSearchText } from "../utils/filterUtils";
import ValueHelpField from "./ValueHelpField";
import "./TestResults.css";

interface TestSummary { id: string; name: string; duration: number; questions: number; totalAttempts: number; avgScore: number; passRate: number }
interface CandidateResult { id: string; userId: string; userName: string; percentage: number; scoredMarks: number; totalMarks: number; passed: boolean; submittedAt: string; timeSpentSec: number; percentile?: number }
interface ReviewItem { questionId: string; isCorrect: boolean; userAnswer: string | string[]; marks: number; section: string }
interface ResultDetail extends CandidateResult { examName: string; sectionWise: Record<string,{total:number;scored:number}>; questionReview: ReviewItem[] }
interface Overview { scoreBands:Array<{label:string;count:number}>;trend:Array<{date:string;attempts:number;avgScore:number}>;toppers:Array<{resultId:string;examId:string;testName:string;userId:string;userName:string;percentage:number;marks:number;timeSpentSec:number}> }

const TestResults: React.FC = () => {
  const [tests,setTests]=useState<TestSummary[]>([]);
  const [selectedTest,setSelectedTest]=useState<TestSummary|null>(null);
  const [candidates,setCandidates]=useState<CandidateResult[]>([]);
  const [detail,setDetail]=useState<ResultDetail|null>(null);
  const [search,setSearch]=useState("");
  const [loading,setLoading]=useState(true);
  const [overview,setOverview]=useState<Overview>({scoreBands:[],trend:[],toppers:[]});

  useEffect(()=>{Promise.all([apiGet<{tests:TestSummary[]}>("/admin/results/tests"),apiGet<Overview>("/admin/results/overview")]).then(([testResponse,overviewResponse])=>{setTests(testResponse.tests||[]);setOverview(overviewResponse)}).catch(console.error).finally(()=>setLoading(false))},[]);
  const openTest=async(test:TestSummary)=>{setSelectedTest(test);setDetail(null);setLoading(true);try{const response=await apiGet<{results:CandidateResult[]}>(`/admin/results/tests/${test.id}/users`);setCandidates(response.results||[])}finally{setLoading(false)}};
  const openCandidate=async(candidate:CandidateResult)=>{setLoading(true);try{const response=await apiGet<{result:ResultDetail}>(`/admin/results/${candidate.id}`);setDetail(response.result)}finally{setLoading(false)}};
  const visible=useMemo(()=>{const query=normalizeSearchText(search);return tests.filter(test=>!query||normalizeSearchText(`${test.name} ${test.duration} minutes ${test.questions} questions ${test.totalAttempts} attempts ${test.avgScore}% average ${test.passRate}% pass rate`).includes(query))},[tests,search]);
  const attempted=tests.filter(test=>test.totalAttempts>0);
  const totalAttempts=tests.reduce((sum,test)=>sum+test.totalAttempts,0);
  const weightedAvg=totalAttempts?tests.reduce((sum,test)=>sum+test.avgScore*test.totalAttempts,0)/totalAttempts:0;
  const weightedPass=totalAttempts?tests.reduce((sum,test)=>sum+test.passRate*test.totalAttempts,0)/totalAttempts:0;
  const formatTime=(seconds:number)=>`${Math.floor(seconds/60)}m ${seconds%60}s`;
  const openTopper=async(topper:Overview["toppers"][number])=>{const test=tests.find(item=>item.id===topper.examId);if(!test)return;setSelectedTest(test);setLoading(true);try{const response=await apiGet<{result:ResultDetail}>(`/admin/results/${topper.resultId}`);setDetail(response.result)}finally{setLoading(false)}};

  if(detail)return <CandidateAnalytics detail={detail} test={selectedTest!} onBack={()=>setDetail(null)} formatTime={formatTime}/>;
  if(selectedTest)return <section className="admin-analytics"><header className="analytics-head"><div><button className="analytics-back" onClick={()=>{setSelectedTest(null);setCandidates([])}}>← All tests</button><span>TEST ANALYTICS</span><h1>{selectedTest.name}</h1><p>Candidate performance, completion and score distribution.</p></div></header><div className="analytics-kpis"><Metric label="Attempts" value={selectedTest.totalAttempts}/><Metric label="Average score" value={`${selectedTest.avgScore.toFixed(1)}%`}/><Metric label="Pass rate" value={`${selectedTest.passRate.toFixed(1)}%`}/><Metric label="Questions" value={selectedTest.questions}/></div><div className="analytics-split"><article className="analytics-card"><h3>Outcome distribution</h3><div className="distribution"><div className="donut" style={{"--pass":`${selectedTest.passRate*3.6}deg`} as React.CSSProperties}><strong>{selectedTest.passRate.toFixed(0)}%</strong><span>passed</span></div><div><span><i className="pass"/>Passed <b>{Math.round(selectedTest.totalAttempts*selectedTest.passRate/100)}</b></span><span><i className="fail"/>Needs improvement <b>{selectedTest.totalAttempts-Math.round(selectedTest.totalAttempts*selectedTest.passRate/100)}</b></span></div></div></article><article className="analytics-card"><h3>Paper information</h3><dl className="paper-details"><div><dt>Duration</dt><dd>{selectedTest.duration} minutes</dd></div><div><dt>Total questions</dt><dd>{selectedTest.questions}</dd></div><div><dt>Average completion</dt><dd>{candidates.length?formatTime(Math.round(candidates.reduce((s,c)=>s+c.timeSpentSec,0)/candidates.length)):"—"}</dd></div></dl></article></div><div className="candidate-results-card"><div className="candidate-results-head"><div><h3>Student results</h3><p>Select a student to open their complete report.</p></div><strong>{candidates.length} attempts</strong></div>{loading?<Empty text="Loading candidate results…"/>:candidates.length===0?<Empty text="No students have completed this test yet."/>:<div className="candidate-results-table"><table><thead><tr><th>Student</th><th>Score</th><th>Percentage</th><th>Time spent</th><th>Submitted</th><th>Result</th><th></th></tr></thead><tbody>{[...candidates].sort((a,b)=>b.percentage-a.percentage).map(candidate=><tr key={candidate.id}><td><div className="analytics-student"><span>{candidate.userName.charAt(0).toUpperCase()}</span><div><strong>{candidate.userName}</strong><small>{candidate.userId}</small></div></div></td><td>{candidate.scoredMarks} / {candidate.totalMarks}</td><td><b>{candidate.percentage.toFixed(1)}%</b></td><td>{formatTime(candidate.timeSpentSec)}</td><td>{candidate.submittedAt?new Date(candidate.submittedAt).toLocaleDateString("en-IN"):"—"}</td><td><span className={`result-state ${candidate.passed?"pass":"fail"}`}>{candidate.passed?"Passed":"Needs improvement"}</span></td><td><button onClick={()=>openCandidate(candidate)}>View report →</button></td></tr>)}</tbody></table></div>}</div></section>;

  return <section className="admin-analytics"><header className="analytics-head"><div><span>PERFORMANCE CENTER</span><h1>Test Analytics</h1><p>Monitor paper performance and open detailed student reports.</p></div><div className="analytics-value-help"><ValueHelpField label="Search Tests" placeholder="Search test, duration or score" value={search} options={tests.map(test=>({value:test.name,label:test.name,keywords:[`${test.duration} minutes`,`${test.questions} questions`,`${test.avgScore}% average`,`${test.passRate}% pass rate`]}))} onChange={setSearch} allowFreeText/></div></header><div className="analytics-kpis overview"><Metric label="Published tests" value={tests.length}/><Metric label="Tests attempted" value={attempted.length}/><Metric label="Student attempts" value={totalAttempts}/><Metric label="Average score" value={`${weightedAvg.toFixed(1)}%`}/><Metric label="Overall pass rate" value={`${weightedPass.toFixed(1)}%`}/></div>{loading?<Empty text="Loading test analytics…"/>:<><OverviewCharts overview={overview} tests={attempted} weightedPass={weightedPass} onTest={openTest} onTopper={openTopper}/><div className="analytics-section-title"><div><h2>Test-wise analytics</h2><p>Select any paper to explore student performance.</p></div><span>{visible.length} tests</span></div><div className="analytics-test-grid">{visible.map(test=><button key={test.id} className="analytics-test-card" onClick={()=>openTest(test)}><div className="analytics-test-top"><span>{test.totalAttempts?"LIVE DATA":"NO ATTEMPTS"}</span><b>→</b></div><h3>{test.name}</h3><p>{test.questions} questions • {test.duration} minutes</p><div className="test-analytics-values"><div><small>Attempts</small><strong>{test.totalAttempts}</strong></div><div><small>Avg. score</small><strong>{test.avgScore.toFixed(1)}%</strong></div><div><small>Pass rate</small><strong>{test.passRate.toFixed(1)}%</strong></div></div><div className="analytics-progress"><i style={{width:`${Math.max(0,Math.min(100,test.avgScore))}%`}}/></div></button>)}</div></>}</section>;
};

const OverviewCharts=({overview,tests,weightedPass,onTest,onTopper}:{overview:Overview;tests:TestSummary[];weightedPass:number;onTest:(test:TestSummary)=>void;onTopper:(topper:Overview["toppers"][number])=>void})=>{
  const maxAttempts=Math.max(1,...overview.trend.map(item=>item.attempts));const maxBand=Math.max(1,...overview.scoreBands.map(item=>item.count));const topTests=[...tests].sort((a,b)=>b.totalAttempts-a.totalAttempts).slice(0,6);
  return <div className="overview-visuals"><article className="analytics-card score-distribution"><header><div><h3>Score distribution</h3><p>Completed attempts grouped by percentage.</p></div><span>ALL RESULTS</span></header><div className="vertical-chart">{overview.scoreBands.map((band,index)=><button key={band.label} title={`${band.count} attempts`}><strong>{band.count}</strong><i style={{height:`${Math.max(8,band.count/maxBand*100)}%`}} className={`band-${index}`}/><small>{band.label}</small></button>)}</div></article><article className="analytics-card outcome-chart"><header><div><h3>Overall outcomes</h3><p>Pass and improvement ratio.</p></div></header><button className="admin-outcome-donut" style={{"--pass":`${weightedPass*3.6}deg`} as React.CSSProperties}><span><strong>{weightedPass.toFixed(0)}%</strong><small>Pass rate</small></span></button><div className="outcome-legend"><span><i/>Passed <b>{weightedPass.toFixed(1)}%</b></span><span><i/>Needs improvement <b>{(100-weightedPass).toFixed(1)}%</b></span></div></article><article className="analytics-card trend-chart"><header><div><h3>Attempt trend</h3><p>Volume and average score by day.</p></div><span>RECENT ACTIVITY</span></header><div className="trend-bars">{overview.trend.length?overview.trend.map(item=><button key={item.date} title={`${item.attempts} attempts · ${item.avgScore}% average`}><b>{item.attempts}</b><i style={{height:`${Math.max(10,item.attempts/maxAttempts*100)}%`}}/><span>{item.avgScore}%</span><small>{item.date}</small></button>):<p>No attempts yet.</p>}</div></article><article className="analytics-card test-comparison"><header><div><h3>Most attempted tests</h3><p>Click a bar to open its detailed report.</p></div></header>{topTests.map(test=><button key={test.id} onClick={()=>onTest(test)}><span>{test.name}</span><div><i style={{width:`${Math.max(5,test.totalAttempts/Math.max(1,topTests[0]?.totalAttempts)*100)}%`}}/></div><b>{test.totalAttempts}</b></button>)}</article><article className="analytics-card topper-leaderboard"><header><div><h3>Top performers</h3><p>Best results across all tests.</p></div><span>TOP 10</span></header>{overview.toppers.length?overview.toppers.map((topper,index)=><button key={topper.resultId} onClick={()=>onTopper(topper)}><em>{index+1}</em><span>{topper.userName.charAt(0).toUpperCase()}</span><div><strong>{topper.userName}</strong><small>{topper.testName}</small></div><b>{topper.percentage.toFixed(1)}%</b><i>→</i></button>):<p className="analytics-empty-small">No completed attempts yet.</p>}</article></div>
};

const CandidateAnalytics=({detail,test,onBack,formatTime}:{detail:ResultDetail;test:TestSummary;onBack:()=>void;formatTime:(seconds:number)=>string})=>{
  const review=detail.questionReview||[];
  const answered=(value:string|string[])=>Array.isArray(value)?value.length>0:Boolean(value);
  const correct=review.filter(item=>item.isCorrect).length;
  const wrong=review.filter(item=>!item.isCorrect&&answered(item.userAnswer)).length;
  const skipped=Math.max(0,review.length-correct-wrong);
  return <section className="admin-analytics candidate-report"><header className="analytics-head"><div><button className="analytics-back" onClick={onBack}>← Student results</button><span>STUDENT PERFORMANCE REPORT</span><h1>{detail.userName}</h1><p>{test.name} • {detail.submittedAt?new Date(detail.submittedAt).toLocaleString("en-IN"):"Completed"}</p></div><span className={`report-outcome ${detail.passed?"pass":"fail"}`}>{detail.passed?"Passed":"Needs improvement"}</span></header><div className="candidate-report-kpis"><div className="admin-score-ring" style={{"--score":`${Math.max(0,detail.percentage)*3.6}deg`} as React.CSSProperties}><div><strong>{detail.percentage.toFixed(1)}%</strong><span>score</span></div></div><Metric label="Marks" value={`${detail.scoredMarks} / ${detail.totalMarks}`}/><Metric label="Time spent" value={formatTime(detail.timeSpentSec)}/><Metric label="Correct" value={correct}/><Metric label="Incorrect" value={wrong}/><Metric label="Unattempted" value={skipped}/></div><div className="candidate-report-grid"><article className="analytics-card section-performance"><h3>Section performance</h3>{Object.entries(detail.sectionWise||{}).map(([section,data])=>{const percent=data.total?data.scored/data.total*100:0;return <div className="section-performance-row" key={section}><div><strong>{section}</strong><span>{data.scored} / {data.total}</span></div><div><i style={{width:`${Math.max(0,Math.min(100,percent))}%`}}/></div><b>{percent.toFixed(1)}%</b></div>})}</article><article className="analytics-card benchmark"><h3>Performance comparison</h3><Compare label="Student" value={detail.percentage} color="#2f6fed"/><Compare label="Test average" value={test.avgScore} color="#24afd0"/><Compare label="Target" value={70} color="#27b487"/><div className="performance-note"><strong>{detail.percentage>=test.avgScore?"Above test average":"Below test average"}</strong><p>{Math.abs(detail.percentage-test.avgScore).toFixed(1)} percentage points {detail.percentage>=test.avgScore?"above":"below"} the cohort average.</p></div></article></div><article className="analytics-card question-analysis"><h3>Question analysis</h3><div className="question-matrix">{review.map((item,index)=><span key={item.questionId||index} className={item.isCorrect?"correct":answered(item.userAnswer)?"wrong":"empty"} title={`Question ${index+1}`}>{index+1}</span>)}</div><div className="matrix-legend"><span><i className="correct"/>Correct ({correct})</span><span><i className="wrong"/>Incorrect ({wrong})</span><span><i className="empty"/>Unattempted ({skipped})</span></div></article></section>;
};
const Metric=({label,value}:{label:string;value:string|number})=><div className="analytics-metric"><span>{label}</span><strong>{value}</strong></div>;
const Empty=({text}:{text:string})=><div className="analytics-empty">{text}</div>;
const Compare=({label,value,color}:{label:string;value:number;color:string})=><div className="compare-row"><div><span>{label}</span><b>{value.toFixed(1)}%</b></div><div><i style={{width:`${Math.max(0,Math.min(100,value))}%`,background:color}}/></div></div>;
export default TestResults;
